apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: retail-cuckoo-go 
  janus-idp.io/tekton: retail-cuckoo-go
  backstage.io/kubernetes-id: retail-cuckoo-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: retail-cuckoo-go
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  