apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: retail-cuckoo-go-gitops
  description: This is GitOps manifest for retail-cuckoo-go   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: retail-cuckoo-go
    janus-idp.io/tekton: retail-cuckoo-go 
    backstage.io/kubernetes-id: retail-cuckoo-go 
    backstage.io/techdocs-ref: dir:. 
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:retail-cuckoo-go
